### ISSUE TITLE
Unraid + Transcoding/Hardware acceleration

### ISSUE THREAD

**Issue by sigh-straits** [Stremio/server-docker#28]
First of all, thanks for the dockerized version of the Stremio Service.
Was able to follow documentation and run it in [Unraid](https://unraid.net/) (if you're not familiar, it is a Linux-based OS for self-hosting servers and NAS). Managed to install some addons and currently able to proxy stream using Stremio Web. So, the main functionality is working.

I saw that `ffmpeg-jellyfin` is being used, and in Unraid I also have a Jellyfin server docker running, with GPU transcoding capabilities (in my specific case using NVIDIA GPU and nvenc). Tried the same docker configuration as described [here](https://docs.linuxserver.io/images/docker-jellyfin/#nvidia) for `stremio-server`, but to no avail. I guess some additional configuration would be necessary, even if similar `ffmpeg` version is available.

Since I'm not that knowledgeable regarding `ffmpeg` and video decoding/transcoding aspects or how the Stremio Service works, I am reaching for extra help... When testing, only CPU is being used, at least I see persistent spiking in CPU usage when watching content, so is there a way to had GPU hardware acceleration/transcoding functionality? Or is this already available and I missed it?

Even if not specifically for Unraid, was someone able to get this working for Linux platform? Any help or feedback welcome.
Thanks.

**Comment by jaruba** [comment]
i'm uncertain of how much i will be able to help as we never tested the case of nvenc in a docker container

the server itself does profiling to attempt to figure out what hwaccel methods are supported on the system

as far as i understand the issue with using hwaccel in docker is that the docker container does not normally have access to the GPU, so i expect the issue to be the fact that our Dockerfile does not give the required access to the GPU

there is a community PR with this minor change: https://github.com/Stremio/server-docker/pull/24/files

that i believe might be specific to giving the required access to use the `nvenc` hwaccel method, but we didn't test it yet, if u could test it and confirm that the change (including the steps u followed from the jellyfin docs) work in your case, then we could potentially merge it

**Comment by Owen000** [comment]
Stremio server needs to be open source, I'm working on fixing this but it would be so much easier if it was open source.

**Comment by Owen000** [comment]
After some debugging I was able to track down whats causing the issue in my setup

`Impossible to convert between the formats supported by the filter 'graph -1 input from stream 0:0' and the filter 'auto_scale_0'
[vf#0:0 @ 0x55a3482e2140] Error reinitializing filters!
[vf#0:0 @ 0x55a3482e2140] Task finished with error code: -38 (Function not implemented)
[vf#0:0 @ 0x55a3482e2140] Terminating thread with return code -38 (Function not implemented)
[vost#0:0/hevc_nvenc @ 0x55a3482d3b00] Could not open encoder before EOF
[vost#0:0/hevc_nvenc @ 0x55a3482d3b00] Task finished with error code: -22 (Invalid argument)
[vost#0:0/hevc_nvenc @ 0x55a3482d3b00] Terminating thread with return code -22 (Invalid argument)
[out#0/matroska @ 0x55a3482d4e40] Nothing was written into output file, because at least one of its streams received no packets.`

(This is using the same ffmpeg commands the test for verifying it's working is using)
I've looked at fixes and none seem to work for me.

**Comment by xeroxmalf** [comment]
I got it working by using the newer Nvidia container toolkit and this for my compose:

```
stremio:
    container_name: stremio
    image: stremio/server:latest
    restart: unless-stopped
    pull_policy: always
    runtime: nvidia
    network_mode: host
    volumes:
      - /docker-configs/stremio:/root/.stremio-server
    environment:
      - NO_CORS=1
      - CASTING_DISABLED=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - FFMPEG_BIN=/usr/lib/jellyfin-ffmpeg/ffmpeg
      - FFPROBE_BIN=/usr/lib/jellyfin-ffmpeg/ffprobe
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jellyfin-ffmpeg
```

```
hls-converter - Testing video hw accel for profile: nvenc-linux
-> GET /hlsv2/11470-nvenc-linux-video-hevc.mkv/video0.m3u8?mediaURL=http%3A%2F%2F192.168.250.125%3A11470%2Fsamples%2Fhevc.mkv&profile=nvenc-linux&maxWidth=1200
-> GET /samples/hevc.mkv
-> GET /samples/hevc.mkv bytes=0-
-> OPTIONS /get-https?authKey=snipped&ipAddress=192.168.250.125
-> GET /get-https?authKey=snipped&ipAddress=192.168.250.125
-> GET /hlsv2/11470-nvenc-linux-video-hevc.mkv/destroy
hls-converter 11470-nvenc-linux-video-hevc.mkv has been requested to be destroyed
hls-converter 11470-nvenc-linux-video-hevc.mkv destoyed
hls-converter - Tests passed for [video] hw accel profile: nvenc-linux
hls-converter - All tests passed for hw accel profile: nvenc-linux
```

```
docker exec -it stremio nvidia-smi
Fri Dec 13 05:21:57 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060 6GB    On  |   00000000:08:00.0 Off |                  N/A |
|  0%   32C    P8              9W /  150W |       3MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+.
```

**Comment by Alistair1231** [comment]
For future reference, I got it working using Intel's QSV with this compose:

```yml
services:
  stremio:
    container_name: stremio
    image: stremio/server:latest
    ports:
      - 11470:11470
      - 12470:12470
    volumes:
      - ./config:/config
    devices:
      - /dev/dri:/dev/dri
    environment:
      - VAAPI_DEVICE=/dev/dri/renderD128
      - APP_PATH=/config
      #- NO_CORS=0
```

Make sure your host has the correct drivers installed, e.g. on Ubuntu:
```bash
sudo apt-get update
sudo apt-get install -y intel-media-va-driver-non-free vainfo intel-gpu-tools
```
